const {
  memberId,
  exchangeRate,
  anonymousUser,
  orderShippingInfo,
  shippingStatusType,
  exchangeProdAmountCharge,
  exchangeDiscountMoney,
  exchangeDeliveryMoney,
  exchangeTotalMoney,
  basketVO,
  countryVO,
  membershipVO,
  errMsg,
  statusChangedFail,
  cancelResult,
} = window.__INITIAL_STATE__

export default {
  errMsg,
  memberId,
  exchangeRate,
  anonymousUser,
  orderShippingInfo,
  shippingStatusType,
  exchangeProdAmountCharge,
  exchangeDiscountMoney,
  exchangeDeliveryMoney,
  exchangeTotalMoney,
  statusChangedFail,
  cancelResult,
  basket: basketVO,
  country: countryVO,
  membership: membershipVO,
}
