export const EMAILS = [
  'daum.net',
  'hanmail.net',
  'naver.com',
  'gmail.com',
  'nate.com',
  'hotmail.com',
  'paran.com',
  'chol.com',
  'korea.com',
  'dreamwiz.com',
  'empal.com',
  'freechal.com',
  'hanafos.com',
]
