<template>
  <fieldset>
    <input type="hidden"
           name="payMethodType"
           :value="fieldset.payMethodType" />
    <input type="hidden"
           name="bsSeqList"
           :value="fieldset.bsSeqList">
    <input type="hidden"
           name="accesstype"
           :value="fieldset.accesstype" />
    <input type="hidden"
           name="goodname"
           :value="fieldset.goodname" />
    <input type="hidden"
           name="originalAmt"
           :value="fieldset.originalAmt" />
    <input type="hidden"
           name="paymentAccountNotDeli"
           :value="fieldset.paymentAccountNotDeli" />
    <input type="hidden"
           name="acceptmethod"
           :value="fieldset.acceptmethod" />
    <input type="hidden"
           name="currency"
           :value="fieldset.currency" />
    <input type="hidden"
           name="oid"
           :value="fieldset.oid" />
    <input type="hidden"
           name="ini_logoimage_url"
           :value="fieldset.ini_logoimage_url" />
    <input type="hidden"
           name="ini_menuarea_url"
           :value="fieldset.ini_menuarea_url">
    <input type="hidden"
           name="ini_encfield"
           :value="fieldset.ini_encfield" />
    <input type="hidden"
           name="ini_certid"
           :value="fieldset.ini_certid" />
    <input type="hidden"
           name="ini_paymethod"
           :value="fieldset.ini_paymethod" />
    <input type="hidden"
           name="quotainterest"
           :value="fieldset.quotainterest">
    <input type="hidden"
           name="paymethod"
           :value="fieldset.paymethod" />
    <input type="hidden"
           name="cardcode"
           :value="fieldset.cardcode">
    <input type="hidden"
           name="cardquota"
           :value="fieldset.cardquota">
    <input type="hidden"
           name="rbankcode"
           :value="fieldset.rbankcode">
    <input type="hidden"
           name="reqsign"
           :value="fieldset.reqsign">
    <input type="hidden"
           name="encrypted"
           :value="fieldset.encrypted">
    <input type="hidden"
           name="sessionkey"
           :value="fieldset.sessionkey">
    <input type="hidden"
           name="uid"
           :value="fieldset.uid">
    <input type="hidden"
           name="sid"
           :value="fieldset.sid">
    <input type="hidden"
           name="version"
           :value="fieldset.version">
    <input type="hidden"
           name="clickcontrol"
           :value="fieldset.clickcontrol">
    <input type="hidden"
           name="gopaymethod"
           :value="fieldset.gopaymethod" />
    <input type="hidden"
           name="buyername"
           :value="buyer.oaBuyerName" />
    <input type="hidden"
           name="buyeremail"
           :value="buyer.oaBuyerEmail" />
    <input type="hidden"
           name="buyertel"
           :value="buyer.oaBuyerPhone" />
    <input type="hidden"
           name="P_APP_BASE"
           :value="fieldset.P_APP_BASE" />
    <input type="hidden"
           name="P_MID"
           :value="fieldset.P_MID" />
    <input type="hidden"
           name="P_OID"
           :value="fieldset.P_OID" />
    <input type="hidden"
           name="P_AMT"
           :value="fieldset.P_AMT" />
    <input type="hidden"
           name="P_MNAME"
           :value="fieldset.P_MNAME" />
    <input type="hidden"
           name="P_UNAME"
           :value="fieldset.P_UNAME" />
    <input type="hidden"
           name="P_GOODS"
           :value="fieldset.P_GOODS" />
    <input type="hidden"
           name="P_NOTI"
           :value="fieldset.P_NOTI" />
    <input type="hidden"
           name="P_HPP_METHOD"
           :value="fieldset.P_HPP_METHOD" />
    <input type="hidden"
           name="P_MOBILE"
           :value="fieldset.P_MOBILE" />
    <input type="hidden"
           name="P_BUYERMOBILE"
           :value="fieldset.P_BUYERMOBILE" />
    <input type="hidden"
           name="P_EMAIL"
           :value="fieldset.P_EMAIL" />
    <input type="hidden"
           name="P_RESERVED"
           :value="fieldset.P_RESERVED" />
    <input type="hidden"
           name="P_CHARSET"
           :value="fieldset.P_CHARSET" />
    <input type="hidden"
           name="P_NEXT_URL"
           :value="fieldset.P_NEXT_URL" />
    <input type="hidden"
           name="P_NOTI_URL"
           :value="fieldset.P_NOTI_URL" />
    <input type="hidden"
           name="P_RETURN_URL"
           :value="fieldset.P_RETURN_URL" />
    <input v-if="$LANG === 'en'"
           type="hidden"
           name="P_LANG"
           value="en" />
    <input type="hidden"
           name="PayMethod"
           :value="fieldset.PayMethod" />
    <input type="hidden"
           name="GoodsCnt"
           :value="fieldset.GoodsCnt" />
    <input type="hidden"
           name="GoodsName"
           :value="fieldset.GoodsName" />
    <input type="hidden"
           name="Amt"
           :value="fieldset.Amt" />
    <input type="hidden"
           name="supplyAmt"
           :value="fieldset.supplyAmt" />
    <input type="hidden"
           name="goodsVat"
           :value="fieldset.goodsVat" />
    <input type="hidden"
           name="ServiceAmt"
           :value="fieldset.ServiceAmt" />
    <input type="hidden"
           name="BuyerName"
           :value="buyer.oaBuyerName" />
    <input type="hidden"
           name="BuyerEmail"
           :value="buyer.oaBuyerEmail" />
    <input type="hidden"
           name="certifiedFlag"
           :value="fieldset.certifiedFlag" />
    <input type="hidden"
           name="merchantEncKey"
           :value="fieldset.merchantEncKey" />
    <input type="hidden"
           name="merchantHashKey"
           :value="fieldset.merchantHashKey" />
    <input type="hidden"
           name="requestDealApproveUrl"
           :value="fieldset.requestDealApproveUrl" />
    <input type="hidden"
           name="merchantTxnNum"
           :value="fieldset.merchantTxnNum" />
    <input type="hidden"
           name="AuthFlg"
           :value="fieldset.AuthFlg" />
    <input type="hidden"
           name="prType"
           :value="fieldset.prType" />
    <input type="hidden"
           name="channelType"
           :value="fieldset.channelType" />
    <input type="hidden"
           name="possiCard"
           :value="fieldset.possiCard" />
    <input type="hidden"
           name="maxInt"
           :value="fieldset.maxInt" />
    <input type="hidden"
           name="fixedInt"
           :value="fieldset.fixedInt" />
    <input type="hidden"
           name="noIntYN"
           :value="fieldset.noIntYN" />
    <input type="hidden"
           name="noIntOpt"
           :value="fieldset.noIntOpt" />
    <input type="hidden"
           name="pointUseYn"
           :value="fieldset.pointUseYn" />
    <input type="hidden"
           name="blockCard"
           :value="fieldset.blockCard" />
    <input type="hidden"
           name="resultCode"
           :value="fieldset.resultCode" />
    <input type="hidden"
           name="resultMsg"
           :value="fieldset.resultMsg" />
    <input type="hidden"
           name="txnId"
           :value="fieldset.txnId" />
    <input type="hidden"
           name="prDt"
           :value="fieldset.prDt" />
    <input type="hidden"
           name="EdiDate"
           :value="fieldset.EdiDate" />
    <input type="hidden"
           name="EncryptData"
           :value="fieldset.EncryptData" />
    <input type="hidden"
           name="SPU"
           :value="fieldset.SPU" />
    <input type="hidden"
           name="SPU_SIGN_TOKEN"
           :value="fieldset.SPU_SIGN_TOKEN" />
    <input type="hidden"
           name="MPAY_PUB"
           :value="fieldset.MPAY_PUB" />
    <input type="hidden"
           name="NON_REP_TOKEN"
           :value="fieldset.NON_REP_TOKEN" />
    <input type="hidden"
           name="giftCardNumber"
           :value="fieldset.giftCardNumber" />
    <input type="hidden"
           name="giftCardAmount"
           :value="fieldset.giftCardAmount" />
    <input type="hidden"
           name="paymentAmount"
           :value="fieldset.paymentAmount" />
    <input type="hidden"
           name="osDeliMoenyUse"
           :value="fieldset.osDeliMoenyUse" />
    <input type="hidden"
           name="deliveryCharge"
           :value="fieldset.deliveryCharge">
    <input type="hidden"
           name="ordDeliveryCharge"
           :value="fieldset.ordDeliveryCharge">
    <input type="hidden"
           name="osDeliType"
           :value="fieldset.osDeliType">
    <input type="hidden"
           name="osDeliPayType"
           :value="fieldset.osDeliPayType">
    <input type="hidden"
           name="payaplSaleId"
           :value="fieldset.payaplSaleId">
    <input type="hidden"
           name="paypalPaymentId"
           :value="fieldset.paypalPaymentId">
    <input type="hidden"
           name="paypalPayerId"
           :value="fieldset.paypalPayerId">
    <input type="hidden"
           name="paypalPayerEmail"
           :value="fieldset.paypalPayerEmail">
    <input type="hidden"
           name="paypalCreateTime"
           :value="fieldset.paypalCreateTime">
    <input type="hidden"
           name="giftCardCodes"
           :value="discount.giftCardCodes" />
    <input type="hidden"
           name="oaBuyerEmail"
           :value="buyer.oaBuyerEmail">
    <input type="hidden"
           name="oaCountryName"
           :value="shipping.oaCountryName">
    <input type="hidden"
           name="oaEmail"
           :value="shipping.oaEmail">
    <input type="hidden"
           name="oaPhone"
           :value="shipping.oaPhone">
    <input type="hidden"
           name="oaZoneCode"
           :value="shipping.zoneCode">
    <input type="hidden"
           name="oaAddr1"
           :value="shipping.oaAddr1">
    <input type="hidden"
           name="oaAddr2"
           :value="shipping.oaAddr2">
    <input type="hidden"
           name="oaAddr3"
           :value="shipping.oaAddr3">
    <input type="hidden"
           name="defaultAddressType"
           :value="shipping.defaultAddressType">
    <input type="hidden"
           name="changeNationType"
           :value="shipping.changeNationType">
    <input type="hidden"
           name="oaBuyerCountryName"
           :value="buyer.oaBuyerCountryName">
    <input type="hidden"
           name="oaBuyerCountryCode"
           :value="buyer.oaBuyerCountryCode">
    <input type="hidden"
           name="oaBuyerPhone"
           :value="buyer.oaBuyerPhone">
    <input type="hidden"
           name="oaBuyerName"
           :value="buyer.oaBuyerName">
    <input type="hidden"
           name="pointPrice"
           :value="discount.pointPrice">
  </fieldset>
</template>

<script>
  import { mapGetters, mapState } from 'vuex'

  export default {
    name: 'form-hidden',
    computed: {
      ...mapState(['fieldset']),
      ...mapGetters(['payment', 'buyer', 'shipping', 'discount'])
    }
  }
</script>
