const {
  memberId,
  exchangeRate,
  anonymousUser,
  orderShippingInfo,
  shippingStatusType,
  exchangeProdAmountCharge,
  exchangeDiscountMoney,
  exchangeDeliveryMoney,
  exchangeTotalMoney,
  basketVO,
  countryVO,
  membershipVO,
  orderAddDeli,
  errMsg,
  cancelResult,
  statusChangedFail,
  complete,
} = window.__INITIAL_STATE__

export default {
  errMsg,
  memberId,
  exchangeRate,
  anonymousUser,
  orderShippingInfo,
  shippingStatusType,
  exchangeProdAmountCharge,
  exchangeDiscountMoney,
  exchangeDeliveryMoney,
  exchangeTotalMoney,
  orderAddDeli,
  cancelResult,
  statusChangedFail,
  complete,
  basket: basketVO,
  country: countryVO,
  membership: membershipVO,
  payType: 'kakaopay',
  inicis: {
    inicisEncfield: '',
    inicisTid: '',
    orderNumber: '',
    paymentGateway: '',
  },
}
